# Site Configuration
baseURL = "https://dapr-cn.github.io/docs/"
title = "Dapr 中文文档"
theme = "docsy"

enableRobotsTXT = true
enableGitInfo = true

# Language Configuration
languageCode = "zh-cn"
contentDir = "content/zh"
defaultContentLanguage = "zh"

# Disable categories & tags
disableKinds = ["taxonomy", "term"]

# Google Analytics
[services.googleAnalytics]
id = "UA-149338238-3"

# Markdown Engine - Allow inline html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Top Nav Bar
[[menu.main]]
    name = "官网"
    weight = 40
    url = "https://dapr.io"
[[menu.main]]
    name = "关于"
    weight = 50
    url = "https://dapr.io/#about"
[[menu.main]]
    name = "下载"
    weight = 60
    url = "https://dapr.io/#download"
[[menu.main]]
    name = "博客"
    weight = 70
    url = "https://blog.dapr.io/posts"
[[menu.main]]
    name = "社区"
    weight = 80
    url = "https://dapr.io/#community"
[[menu.main]]
    name = "英文文档"
    weight = 80
    url = "https://docs.dapr.io/"


[params]
copyright = "Dapr"
#privacy_policy = "https://policies.google.com/privacy"

# Algolia
algolia_docsearch = true
offlineSearch = false

# GitHub Information
github_repo = "https://github.com/dapr-cn/docs"
github_project_repo = "https://github.com/dapr/dapr"
github_subdir = "daprdocs"
github_branch = "v0.11"

# Versioning
version_menu = "v0.11 (latest)"
version = "v0.11"
archived_version = false

[[params.versions]]
  version = "v1.0-rc.2 (preview)"
  url = "https://v1-rc2.docs.dapr.io"
[[params.versions]]
  version = "v0.11 (latest)"
  url = "#"
[[params.versions]]
  version = "v0.10"
  url = "https://github.com/dapr/docs/tree/v0.10.0"
[[params.versions]]
  version = "v0.9"
  url = "https://github.com/dapr/docs/tree/v0.9.0"
[[params.versions]]
  version = "v0.8"
  url = "https://github.com/dapr/docs/tree/v0.8.0"

# UI Customization
[params.ui]
sidebar_menu_compact = true
navbar_logo = true
sidebar_search_disable = true

# Links
## End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/daprdev"
	icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest updates!"
[[params.links.user]]
	name = "YouTube"
	url = "https://www.youtube.com/channel/UCtpSQ9BLB_3EXdWAUQYwnRA"
	icon = "fab fa-youtube"
  desc = "Community call recordings and other cool demos"
[[params.links.user]]
	name = "博客"
	url = "https://blog.dapr.io/posts"
	icon = "fas fa-blog"
  desc = "Community call recordings and other cool demos"
## Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/dapr/"
	icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
	name = "Discord"
	url = "https://aka.ms/dapr-discord"
	icon = "fab fa-discord"
  desc = "Conversations happen here!"
[[params.links.developer]]
	name = "Zoom"
	url = "https://aka.ms/dapr-community-call"
	icon = "fas fa-video"
  desc = "Meetings happen here!"
