name: github pages deploy

on:
  push:
    branches:
      - v1.0/publish_translate_site

jobs:
  delpoy_github:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Setup Docsy and Build
        run: |
          git submodule update --init --recursive 
          cd daprdocs
          chmod a+x ./update_config_zh.sh
          ./update_config_zh.sh
          sed -i 's/languageCode = "en-us"/defaultContentLanguage = "zh-hans"/g' config.toml
          sudo npm install --save
          hugo --minify

      - name: Deploy Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: dapr-cn/dapr-cn.github.io
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: daprdocs/public

      - name: Sync from Github to Gitee
        uses: homerjam/git-sync-alternate@1.0.2
        with:
          source_repo: "dapr-cn/dapr-cn.github.io"
          destination_repo: "git@gitee.com:dapr-cn/dapr-cn.git"
          source_branch: "gh-pages" # [regexp] optional, will sync all by default
          destination_branch: "gh-pages" # [string] optional, will sync all by default
          # ssh_private_key: ${{ secrets.ACTIONS_DEPLOY_KEY_GITEE }} # optional
          # source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.ACTIONS_DEPLOY_KEY_GITEE }} # optional, will override `SSH_PRIVATE_KEY`
          commit_user_email: dapr@dapr.io # optional, will trigger 'git-sync' commit
          commit_user_name: dapr-cn # optional, will trigger 'git-sync' commit
          # sync_tags: ${{ secrets.SYNC_TAGS }} # optional, will sync all tags
